StarCinema/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using StarCinema.DataLayer.Abstract;
using StarCinema.DomainModels;
using StarCinema.Models;
using StarCinema.Models.CRUDModels;
using StarCinema.Models.CRUDModels.CategoryModels;

namespace StarCinema.Controllers.CRUDControllers
{
    public class CategoryController : Controller
    {
        private readonly IMovieRepository _movieRepo;
        private readonly ICategoryRepository _categoryRepo;
        private readonly CategoryFactory _categoryFactory;
        private readonly IConfiguration _config;
        private int _itemsPerPage;

        public CategoryController(IMovieRepository movieRepo, ICategoryRepository categoryRepo, CategoryFactory categoryFactory, IConfiguration configuration)
        {
            this._movieRepo = movieRepo; 
            this._categoryRepo = categoryRepo;
            this._categoryFactory = categoryFactory;
            this._config = configuration;
            this._itemsPerPage = _config.GetValue<int>("ItemsPerPage");

        }

        [HttpGet]
        [Authorize]
        public IActionResult Categories([FromQuery] CategoryListingRequest request)
        {
            var categories = _categoryRepo.PaginatedCategories(request.Page, request.PageSize, request.OrderBy).ToList();
            var allCategoriesCount =  _categoryRepo.CategoriesCount();
            var categoriesViewModelList = new List<CategoryViewModel>();
            
            categories.ForEach(x => categoriesViewModelList.Add(new CategoryViewModel(x)));

            var categoriesViewModel = new ListingViewModel<CategoryViewModel>(categoriesViewModelList, request.Page, allCategoriesCount, request.OrderBy);

            return View(categoriesViewModel);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult RemoveCategory(int categoryId)
        {
            var removedCategory = _categoryRepo.RemoveCategory(categoryId);
            return RedirectToAction("Categories");
        }

        [Authorize(Roles = "Admin")]
        public ActionResult AddCategory()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult AddCategory(CategoryViewModel category)
        {
            if (ModelState.IsValid)
            {
                var categoryToAdd = _categoryFactory.GetCategory(category);
                _categoryRepo.AddCategory(categoryToAdd);
                return RedirectToAction("Categories");
            }
            return View(category);
        }

        private  IList<CategoryViewModel> getAllCategories()
        {
            var allCategories = _categoryRepo.AllCategories().ToList();
            var categoriesViewModel = new List<CategoryViewModel>();
            allCategories.ForEach(x => categoriesViewModel.Add(new CategoryViewModel(x)));
            return categoriesViewModel;
        }

    }
}

StarCinema/Controllers/CityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using StarCinema.DataLayer.Abstract;
using StarCinema.DomainModels;
using StarCinema.Models;
using StarCinema.Models.CRUDModels;
using StarCinema.Models.CRUDModels.CityModels;

namespace StarCinema.Controllers.CRUDControllers
{
    public class CityController : Controller
    {
        private readonly ICityRepository _repo;
        private readonly CityFactory _cityFactory;
        private readonly IConfiguration _config;
        private int _itemsPerPage;
        public CityController(ICityRepository cityRepo, CityFactory cityFactory, IConfiguration configuration)
        {
            this._repo = cityRepo;
            this._cityFactory = cityFactory;
            this._config = configuration;
            this._itemsPerPage = _config.GetValue<int>("ItemsPerPage");
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult AddCity()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult AddCity(CityViewModel city)
        {
            if (!ModelState.IsValid)
            {
                return View("AddCity", city);
            }
            var cityToAdd = _cityFactory.GetCity(city);
            _repo.AddCity(cityToAdd);
            return RedirectToAction("Cities");
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Cities(CityListingRequest request)
        {
            var cities = _repo.PaginatedCities(request.Page, request.PageSize, request.OrderBy).ToList();            
            int citiesCount = _repo.CitiesCount();

            var citiesViewModelList = new List<CityViewModel>();
            cities.ForEach(x => citiesViewModelList.Add(new CityViewModel(x)));
            
            var paginatedCitiesViewModelList = new ListingViewModel<CityViewModel>(citiesViewModelList, request.Page, citiesCount, request.OrderBy);

            return View(paginatedCitiesViewModelList);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult RemoveCity(int cityId)
        {
            _repo.RemoveCity(cityId);
            return RedirectToAction("Cities");
        }
    }
}

StarCinema/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Cors;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.Extensions.Configuration;
using StarCinema.DataLayer.Abstract;
using StarCinema.DomainModels;
using StarCinema.Models;
using StarCinema.Models.CRUDModels;
using StarCinema.Models.CRUDModels.CommentModels;
using StarCinema.Models.CRUDModels.IndexModels;
using StarCinema.Models.CRUDModels.MovieModels;
using StarCinema.Models.CRUDModels.RateModels;
using StarCinema.Models.IndexModels;

namespace StarCinema.Controllers.CRUDControllers
{
    public class MovieController : Controller
    {
        private readonly IMovieRepository _movieRepo;
        private readonly IUserRepository _usrRepo;
        private readonly ICategoryRepository _categoryRepo;
        private readonly IRateRepository _rateRepo;
        private readonly ICommentRepository _commentRepo;
        private readonly MovieFactory _movieFactory;
        private readonly CommentFactory _commentFactory;
        private readonly IConfiguration _config;
        private int _itemsPerPage;

        public MovieController(IMovieRepository movieRepo, IUserRepository usrRepo, ICategoryRepository categoryRepo, 
            IRateRepository rateRepo, ICommentRepository commentRepo, MovieFactory movieFactory, CommentFactory commentFactory, IConfiguration configuration)
        {
            this._movieRepo = movieRepo;
            this._usrRepo = usrRepo;
            this._categoryRepo = categoryRepo;
            this._rateRepo = rateRepo;
            this._commentRepo = commentRepo;
            this._movieFactory = movieFactory;
            this._commentFactory = commentFactory;
            this._config = configuration;
            this._itemsPerPage = _config.GetValue<int>("ItemsPerPage");
        }
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Movies(MovieListingRequest request)
        {
            var movies = _movieRepo.PaginatedMovies(request.Page, request.PageSize, request.OrderBy).ToList();            
            int moviesCount = this._movieRepo.MoviesCount();

            var moviesViewModel = new List<MovieListingViewModel>();

            movies.ForEach(x => moviesViewModel.Add(new MovieListingViewModel(x)));

            var paginatedMovies = new ListingViewModel<MovieListingViewModel>(moviesViewModel, request.Page, moviesCount, "TitleAsc");
            return View(paginatedMovies);
        }

        [HttpGet]
        public IActionResult MoviesFromCategory(int categoryId)
        {
            var movies = this._categoryRepo.FindMoviesFromCategory(categoryId);
            var categoryName = _categoryRepo.FindCategory(categoryId).CategoryName;
            var moviesViewModel = new MoviesFromCategoryViewModel()
            {
                CategoryName = categoryName,
                MoviesFromCategory = movies
            };

            return View(moviesViewModel);
        }

        public IActionResult ShowMovie(ShowMovieRequest request)
        {
            var movie = this._movieRepo.FindMovie(request.MovieId);
            var comments = this._commentRepo.PaginatedComments(request.MovieId, request.CommentPage, request.PageSize, "AddedDateDesc").ToList();

            var movieViewModel = new ShowMovieViewModel(movie, request.CommentPage, movie.Comments.Count());
            comments.ForEach(x => movieViewModel.Comments.Add(new ShowMovieCommentViewModel(x)));
            movieViewModel.CanUserRate = TempData["RateErrorData"] == null ? true : false;
            movieViewModel.AddComentViewModel.MovieId = request.MovieId;

            TempData["RateErrorData"] = null;
            return View(movieViewModel);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult AddMovie()
        {
            var categories = this._categoryRepo.AllCategories().ToList();
            return View(new AddEditMovieViewModel(categories));
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult AddMovie(AddEditMovieRequest request)
        {
            if (ModelState.IsValid)
            {
                var movieToAdd = _movieFactory.CreateMovie(request);

                _movieRepo.AddMovie(movieToAdd);
                int id = movieToAdd.Id;
                var filePoster = request.PosterImage;
                var fileBanner = request.BannerImage;

                ImagesManager.UploadPoster(filePoster, id, true);
                ImagesManager.UploadBanner(fileBanner, id, true);
                return RedirectToAction("Movies");
            }

            var categories = _categoryRepo.AllCategories().ToList();
            var movie = new AddEditMovieViewModel(categories, request);

            return View(movie);
        }


        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult RemoveMovie(int movieId)
        {
            var movieToDelete =  _movieRepo.FindMovie(movieId); 
            _movieRepo.RemoveMovie(movieId);
            ImagesManager.DeleteImages(movieId);
            return View(movieToDelete);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult EditMovie(int movieId)
        {
            var movie = _movieRepo.FindMovie(movieId);
            var categories = _categoryRepo.AllCategories().ToList();

            return View(new AddEditMovieViewModel(categories, movie));
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public RedirectToActionResult EditMovie(AddEditMovieViewModel addEditMovie)
        {
            var movietoEdit = _movieFactory.CreateMovie(addEditMovie.Request);

            this._movieRepo.EditMovie(addEditMovie.Request.Id, movietoEdit);

            int id = addEditMovie.Request.Id;
            var filePoster = addEditMovie.Request.PosterImage;
            var fileBanner = addEditMovie.Request.BannerImage;
            if (filePoster != null)
            { 
                ImagesManager.UploadPoster(filePoster, id, false);
            }

            if (fileBanner != null)
            { 
                ImagesManager.UploadBanner(fileBanner, id, false);
            }
            return RedirectToAction("Movies");
        }

        [Authorize]
        [HttpPost]
        public RedirectToActionResult AddComment(AddComentRequest request)
        {

            var user = this._usrRepo.GetUser(request.User);
            int id = request.MovieId;
            var commentToAdd = _commentFactory.CreateComment(request);
            
            this._movieRepo.AddComment(request.MovieId, commentToAdd);
            return RedirectToAction("ShowMovie", new ShowMovieRequest(){ MovieId = request.MovieId });
        }

        [Authorize]
        [HttpPost]
        public RedirectToActionResult AddRate(AddRateRequest request)
        {
            this.ViewData["ReturnUrl"] = "";

            var user = this._usrRepo.GetUser(request.Username);
            if (!this._rateRepo.UserRated(request.MovieId, user.Id))
            {            
                Rate rateToAdd = new Rate()
                {
                    User = user,
                    IfLike = request.ThumbUp
                }; 
                _rateRepo.AddRate(request.MovieId, rateToAdd);
                return RedirectToAction("ShowMovie", new ShowMovieRequest() { MovieId = request.MovieId });

            }
            TempData["RateErrorData"] = "You already have rated this addEditMovie";

            return RedirectToAction("ShowMovie", new ShowMovieRequest() {MovieId = request.MovieId});
        }

        [HttpGet]
        public IActionResult SearchMovies(string movieTitle)
        {
            var movies = _movieRepo.SearchMovies(movieTitle);
            var moviesSearchList = new List<SearchMoviesViewModel>();
            movies.ToList().ForEach(x => moviesSearchList.Add(new SearchMoviesViewModel(x)));
            return View(moviesSearchList);
        }
    }
}

StarCinema/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using StarCinema.Areas.Identity.Data;
using StarCinema.DataLayer.Abstract;
using StarCinema.Models;
using StarCinema.Models.CRUDModels.UserModels;

namespace StarCinema.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserRepository _userRepository;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<StarCinemaUser> _userManager;

        public UserController(IUserRepository userRepository, RoleManager<IdentityRole> roleManager, UserManager<StarCinemaUser> userManager)
        {
            _userRepository = userRepository;
            _roleManager = roleManager;
            _userManager = userManager;
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Users(UserListingRequest request)
        {
            var users = _userRepository.GetPaginatedUsers(request.Page, request.PageSize, request.OrderBy).ToList();
            var userListingRows = new List<UserListingRowViewModel>();
            users.ForEach(x => userListingRows.Add(new UserListingRowViewModel(x)));

            foreach (var user in users)
            {
                var userRoles = await _userManager.GetRolesAsync(user);
                if (userRoles.Any(x => x.Equals("Admin")))
                {
                    userListingRows.Where(x => x.Username == user.UserName).FirstOrDefault().IsAdmin = true;
                }
            }
            
            var userListingViewModel = new ListingViewModel<UserListingRowViewModel>(userListingRows, request.Page, _userRepository.GetUsersCount(), request.OrderBy);
            return View(userListingViewModel);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> EditUserRole(string username, bool isAdmin)
        {                
            var user = _userRepository.GetUser(username);

            if (isAdmin)
            {
                await _userManager.AddToRoleAsync(user, "Admin");
                return RedirectToAction("Users");
            }

            await _userManager.RemoveFromRoleAsync(user, "Admin");
            return RedirectToAction("Users");
        }

        [HttpGet]
        public async Task<IActionResult> AddAdmin()
        {
            if (_userRepository.GetUser("Administrator") == null)
            {
                var user = new StarCinemaUser()
                {
                    UserName = "Administrator",
                    Email = "konwasiak@gmail.com",
                    EmailConfirmed = true
                };
                await _userManager.CreateAsync(user, "`3zVhy/5");
                await _userManager.AddToRoleAsync(user, "Admin");
            }

            return RedirectToAction("Users");
        }


    }
}

StarCinema/Views/Shared/_AddCommentPartial.cshtml
@model StarCinema.Models.CRUDModels.CommentModels.AddComentViewModel
@using Microsoft.AspNetCore.Identity
@using StarCinema.Areas.Identity.Data
@inject SignInManager<StarCinemaUser> SignInManager
@inject UserManager<StarCinemaUser> UserManager

@if (SignInManager.IsSignedIn(User))
{
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <form class="app-form" method="post" asp-action="AddComment" asp-controller="Movie">
                <h2><i class="glyphicon glyphicon-comment"></i> Add Comment</h2>
                <div class="form-group">
                    <input type="hidden" asp-for="@Model.Request.User" value="@User.Identity.Name" />
                    <input type="hidden" asp-for="@Model.Request.MovieId" value="@Model.MovieId" />
                    <textarea class="app-form-input comment wide" placeholder="Comment" asp-for="@Model.Request.Comment"></textarea>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-success app-form-submit btn-big">
                        <i class="glyphicon glyphicon-ok-circle"></i> ADD COMMENT
                    </button>
                </div>
            </form>
        </div>
    </div>
    <br />
    
}
else
{
    <div class="row">
        <h2 class="comments-h2">You must be logged in to add comments</h2>
        <br />
        <div class="col-md-6 col-md-offset-3">
            <form method="get" asp-area="Identity" asp-page="/Account/Login">
                <button type="submit" class="btn btn-success app-form-submit btn-big"> <i class="glyphicon glyphicon-user"></i> LOG IN</button>
            </form>
        </div>
    </div>
    <br />

}

StarCinema/Views/Shared/_CRUDLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StarCinema</title>

    <environment include="Development">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
    </environment>
    <script src="~/js/delete.js"></script>

</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">StarCinema</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Category" asp-action="Categories"><i class="glyphicon glyphicon-th"></i> CATEGORIES</a></li>
                    <li><a asp-controller="Movie" asp-action="Movies"><i class="glyphicon glyphicon-film"></i> MOVIES</a></li>
                    <li><a asp-controller="City" asp-action="Cities"><i class="glyphicon glyphicon-stats"></i> CITIES</a></li>
                    <li><a asp-controller="Cinema" asp-action="Cinemas"><i class="glyphicon glyphicon-facetime-video"></i> CINEMAS</a></li>
                    <li><a asp-controller="User" asp-action="Users"><i class="glyphicon glyphicon-user"></i> USERS</a></li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>

    <div class="container">
        @RenderBody()
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

StarCinema/Views/Shared/_CommentsModalPartial.cshtml
@{
    ViewData["Title"] = "_CommentsModalPartial";
}

    <div class="modal fade" id="commentsModal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-xl" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h2 class="h2" id="commentsModalTitle">Comments added to addEditMovie </h2>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="table-responsive">
                        <table class="table" id="commentsTable">
                            <thead>
                                <tr>
                                    <td>#</td>
                                    <td>Date</td>
                                    <td>User</td>
                                    <td>Comment</td>
                                    <td>Action</td>
                                </tr>
                            </thead>
                            <tbody id="commentsTableBody">
                            </tbody>
                        </table>


                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </div>
    </div>

StarCinema/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StarCinema</title>

    <environment include="Development">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="~/js/delete.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" asp-controller="Home" asp-action="Index"><i class="glyphicon glyphicon-star"></i> StarCinema</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <form class="hidden-md navbar-form navbar-left" asp-controller="Movie" asp-action="SearchMovies" method="get">
                    <div class="input-group">
                        <input type="text" name="movieTitle" class="form-control nav-search" placeholder="Search movie">
                    </div>
                    <button type="submit" class="btn btn-danger btn-search">SEARCH</button>
                </form>
                <partial name="_LoginPartial" />
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>

    <div class="container body-container">
        @RenderBody()
    </div>

    <footer >
        <div class="container ">
            <div class="row">
                <div class="col-xs-4 col-xs-offset-4">
                    <h4>More</h4>
                    <ul>
                        <li><a asp-controller="User" asp-action="Users">Admin panel</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>