StarCinema/Controllers/CinemaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using StarCinema.DataLayer.Abstract;
using StarCinema.DomainModels;
using StarCinema.Models;
using StarCinema.Models.CRUDModels.CinemaHallModels;
using StarCinema.Models.CRUDModels.CinemaModels;

namespace StarCinema.Controllers
{
    public class CinemaController : Controller
    {
        private readonly ICinemaRepository _cinemaRepo;
        private readonly ICityRepository _cityRepo;
        private readonly CinemaFactory _cinemaFactory;
        private readonly CinemaHallFactory _cinemaHallFactory;
        private readonly IConfiguration _config;
        private readonly IGeolocationService _geolocationService;
        public CinemaController(ICinemaRepository cinemaRepo, ICityRepository cityRepo, 
            CinemaFactory cinemaFactory, IConfiguration configuration, IGeolocationService geolocationService,
            CinemaHallFactory cinemaHallFactory)
        {
            _cinemaRepo = cinemaRepo;
            _cityRepo = cityRepo;
            _cinemaFactory = cinemaFactory;
            _cinemaHallFactory = cinemaHallFactory;
            _config = configuration;
            _geolocationService = geolocationService;
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Cinemas([FromQuery] CinemaListingRequest request)
        {
            var cinemas =  this._cinemaRepo.PaginatedCinemas(request.Page, request.PageSize, request.OrderBy).ToList();
            int allCinemasCount = this._cinemaRepo.CinemasCount();

            List<CinemaViewModel> cinemasViewModelList = new List<CinemaViewModel>();
            cinemas.ForEach(x => cinemasViewModelList.Add(CinemaViewModel.CreateListCinemaViewModel(x)));

            var cinemasViewModel = new ListingViewModel<CinemaViewModel>(cinemasViewModelList, request.Page, allCinemasCount, request.OrderBy);

            return View(cinemasViewModel);
        }


        [HttpGet]
        public async Task<IActionResult> SearchCinema(string city)
        {
            var cinemas = _cinemaRepo.SearchCinema(city).ToList();
            var cinemasViewModel = new List<SearchCinemaViewModel>();
            cinemas.ForEach(x => cinemasViewModel.Add(new SearchCinemaViewModel(x)));

            foreach (var cinema in cinemasViewModel)
            {
                cinema.Coordinates = await _geolocationService.GetCoordinates(cinema.City, cinema.Street, cinema.BuildingNumber);
            }

            return View(cinemasViewModel);
        }

        [HttpGet]
        [Authorize]
        public IActionResult ChooseCinemaForBooking(int movieId)
        {
            var cinemasWithMovie = _cinemaRepo.FindCinemaWithMovieShows(movieId).ToList();
            var chooseCinemaViewModel = new ChooseCinemaForBookingViewModel(cinemasWithMovie, movieId);
            return View(chooseCinemaViewModel);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult AddCinema()
        {
            var cities = _cityRepo.AllCities("").ToList();
            return View(new AddEditCinemaViewModel(cities));
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult AddHallsToCinema(AddEditCinemaRequest request)
        {            
            request.CreateCinemaHalls();
            return View("AddHallsToCinema", request);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult AddCinema(AddEditCinemaRequest request)
        {
            var cinema = _cinemaFactory.CreateCinema(request);

            _cinemaRepo.AddCinema(cinema);

            return RedirectToAction("Cinemas");
        }


        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult RemoveCinema(int cinemaId)
        {
            this._cinemaRepo.RemoveCinema(cinemaId);
            return RedirectToAction("Cinemas");
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult EditCinema(int cinemaId)
        {
            var cinema = _cinemaRepo.FindCinema(cinemaId);
            var cities = _cityRepo.AllCities("").ToList();
            var editCinemaViewModel = new AddEditCinemaViewModel(cinema, cities);
            return View(editCinemaViewModel);
        }


        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult EditCinema(AddEditCinemaViewModel addEditCinemaViewModel)
        {
            _cinemaRepo.EditCinema(addEditCinemaViewModel.Request.CinemaId, addEditCinemaViewModel.Request);
            return RedirectToAction("Cinemas");
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult AddHallsToExistingCinema(int hallsCount, int cinemaId)
        {
            var addEditCinemaViewModel = new AddEditCinemaViewModel()
            {
                CinemaId = cinemaId,
                CinemaHallsCount = hallsCount
            };

            return View(addEditCinemaViewModel);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult AddHallsToExistingCinema(AddEditCinemaViewModel addEditCinemaViewModel)
        {
            var cinema = _cinemaRepo.FindCinema(addEditCinemaViewModel.Request.CinemaId);
            var newHalls = new List<CinemaHall>();
            addEditCinemaViewModel.Request.CinemaHalls.ForEach(x => newHalls.Add(_cinemaHallFactory.CreateCinemaHall(x)));
            _cinemaRepo.AddHallsToCinema(cinema.Id, newHalls);
            return RedirectToAction("Cinemas");
        }
    }
}

StarCinema/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using StarCinema.DataLayer.Abstract;
using StarCinema.DomainModels;
using StarCinema.Models;
using StarCinema.Models.IndexModels;

namespace StarCinema.Controllers
{
    public class HomeController : Controller
    {
        public IMovieRepository _movieRepo;
        public ICategoryRepository _categoryRepo;

        public HomeController(IMovieRepository movieRepo, ICategoryRepository categoryRepo)
        {
            this._movieRepo = movieRepo;
            this._categoryRepo = categoryRepo;
        }

        public IActionResult Index()
        {
            IndexMoviesListViewModel imlvm = new IndexMoviesListViewModel(_movieRepo.AllMovies(), this._categoryRepo.AllCategories());
            return View(imlvm);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

StarCinema/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Cors;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.Extensions.Configuration;
using StarCinema.DataLayer.Abstract;
using StarCinema.DomainModels;
using StarCinema.Models;
using StarCinema.Models.CRUDModels;
using StarCinema.Models.CRUDModels.CommentModels;
using StarCinema.Models.CRUDModels.IndexModels;
using StarCinema.Models.CRUDModels.MovieModels;
using StarCinema.Models.CRUDModels.RateModels;
using StarCinema.Models.IndexModels;

namespace StarCinema.Controllers.CRUDControllers
{
    public class MovieController : Controller
    {
        private readonly IMovieRepository _movieRepo;
        private readonly IUserRepository _usrRepo;
        private readonly ICategoryRepository _categoryRepo;
        private readonly IRateRepository _rateRepo;
        private readonly ICommentRepository _commentRepo;
        private readonly MovieFactory _movieFactory;
        private readonly CommentFactory _commentFactory;
        private readonly IConfiguration _config;
        private int _itemsPerPage;

        public MovieController(IMovieRepository movieRepo, IUserRepository usrRepo, ICategoryRepository categoryRepo, 
            IRateRepository rateRepo, ICommentRepository commentRepo, MovieFactory movieFactory, CommentFactory commentFactory, IConfiguration configuration)
        {
            this._movieRepo = movieRepo;
            this._usrRepo = usrRepo;
            this._categoryRepo = categoryRepo;
            this._rateRepo = rateRepo;
            this._commentRepo = commentRepo;
            this._movieFactory = movieFactory;
            this._commentFactory = commentFactory;
            this._config = configuration;
            this._itemsPerPage = _config.GetValue<int>("ItemsPerPage");
        }
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Movies(MovieListingRequest request)
        {
            var movies = _movieRepo.PaginatedMovies(request.Page, request.PageSize, request.OrderBy).ToList();            
            int moviesCount = this._movieRepo.MoviesCount();

            var moviesViewModel = new List<MovieListingViewModel>();

            movies.ForEach(x => moviesViewModel.Add(new MovieListingViewModel(x)));

            var paginatedMovies = new ListingViewModel<MovieListingViewModel>(moviesViewModel, request.Page, moviesCount, "TitleAsc");
            return View(paginatedMovies);
        }

        [HttpGet]
        public IActionResult MoviesFromCategory(int categoryId)
        {
            var movies = this._categoryRepo.FindMoviesFromCategory(categoryId);
            var categoryName = _categoryRepo.FindCategory(categoryId).CategoryName;
            var moviesViewModel = new MoviesFromCategoryViewModel()
            {
                CategoryName = categoryName,
                MoviesFromCategory = movies
            };

            return View(moviesViewModel);
        }

        public IActionResult ShowMovie(ShowMovieRequest request)
        {
            var movie = this._movieRepo.FindMovie(request.MovieId);
            var comments = this._commentRepo.PaginatedComments(request.MovieId, request.CommentPage, request.PageSize, "AddedDateDesc").ToList();

            var movieViewModel = new ShowMovieViewModel(movie, request.CommentPage, movie.Comments.Count());
            comments.ForEach(x => movieViewModel.Comments.Add(new ShowMovieCommentViewModel(x)));
            movieViewModel.CanUserRate = TempData["RateErrorData"] == null ? true : false;
            movieViewModel.AddComentViewModel.MovieId = request.MovieId;

            TempData["RateErrorData"] = null;
            return View(movieViewModel);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult AddMovie()
        {
            var categories = this._categoryRepo.AllCategories().ToList();
            return View(new AddEditMovieViewModel(categories));
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult AddMovie(AddEditMovieRequest request)
        {
            if (ModelState.IsValid)
            {
                var movieToAdd = _movieFactory.CreateMovie(request);

                _movieRepo.AddMovie(movieToAdd);
                int id = movieToAdd.Id;
                var filePoster = request.PosterImage;
                var fileBanner = request.BannerImage;

                ImagesManager.UploadPoster(filePoster, id, true);
                ImagesManager.UploadBanner(fileBanner, id, true);
                return RedirectToAction("Movies");
            }

            var categories = _categoryRepo.AllCategories().ToList();
            var movie = new AddEditMovieViewModel(categories, request);

            return View(movie);
        }


        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult RemoveMovie(int movieId)
        {
            var movieToDelete =  _movieRepo.FindMovie(movieId); 
            _movieRepo.RemoveMovie(movieId);
            ImagesManager.DeleteImages(movieId);
            return View(movieToDelete);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult EditMovie(int movieId)
        {
            var movie = _movieRepo.FindMovie(movieId);
            var categories = _categoryRepo.AllCategories().ToList();

            return View(new AddEditMovieViewModel(categories, movie));
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public RedirectToActionResult EditMovie(AddEditMovieViewModel addEditMovie)
        {
            var movietoEdit = _movieFactory.CreateMovie(addEditMovie.Request);

            this._movieRepo.EditMovie(addEditMovie.Request.Id, movietoEdit);

            int id = addEditMovie.Request.Id;
            var filePoster = addEditMovie.Request.PosterImage;
            var fileBanner = addEditMovie.Request.BannerImage;
            if (filePoster != null)
            { 
                ImagesManager.UploadPoster(filePoster, id, false);
            }

            if (fileBanner != null)
            { 
                ImagesManager.UploadBanner(fileBanner, id, false);
            }
            return RedirectToAction("Movies");
        }

        [Authorize]
        [HttpPost]
        public RedirectToActionResult AddComment(AddComentRequest request)
        {

            var user = this._usrRepo.GetUser(request.User);
            int id = request.MovieId;
            var commentToAdd = _commentFactory.CreateComment(request);
            
            this._movieRepo.AddComment(request.MovieId, commentToAdd);
            return RedirectToAction("ShowMovie", new ShowMovieRequest(){ MovieId = request.MovieId });
        }

        [Authorize]
        [HttpPost]
        public RedirectToActionResult AddRate(AddRateRequest request)
        {
            this.ViewData["ReturnUrl"] = "";

            var user = this._usrRepo.GetUser(request.Username);
            if (!this._rateRepo.UserRated(request.MovieId, user.Id))
            {            
                Rate rateToAdd = new Rate()
                {
                    User = user,
                    IfLike = request.ThumbUp
                }; 
                _rateRepo.AddRate(request.MovieId, rateToAdd);
                return RedirectToAction("ShowMovie", new ShowMovieRequest() { MovieId = request.MovieId });

            }
            TempData["RateErrorData"] = "You already have rated this addEditMovie";

            return RedirectToAction("ShowMovie", new ShowMovieRequest() {MovieId = request.MovieId});
        }

        [HttpGet]
        public IActionResult SearchMovies(string movieTitle)
        {
            var movies = _movieRepo.SearchMovies(movieTitle);
            var moviesSearchList = new List<SearchMoviesViewModel>();
            movies.ToList().ForEach(x => moviesSearchList.Add(new SearchMoviesViewModel(x)));
            return View(moviesSearchList);
        }
    }
}

StarCinema/Views/Home/AddDataAsync.cshtml
@model StarCinema.Models.IndexModels.IndexMoviesListViewModel
@{
    ViewData["Title"] = "AddDataAsync";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>AddDataAsync</h2>

@foreach(var m in Model.LatestMovies)
{
    <h1>@m.Title</h1>
    <h2>@m.Category.CategoryName</h2>
    <h3>@m.ReleaseDate</h3>

}

StarCinema/Views/Home/Index.cshtml
@model StarCinema.Models.IndexModels.IndexMoviesListViewModel
@{
    ViewData["Title"] = "Home Page";
}
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    </ol>
    @{
        var path = "images/MoviesPosters/";
    }
    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <div class="item-container-left" style="background:linear-gradient(0deg,rgba(30,30,30,0.3),rgba(30,30,30,0.3)),url(@(path + Model.LatestMovies.ElementAt(0).Id.ToString() + "Index.jpg")">
                <div class="item-content col-md-5">
                    <h2 class="carousel-h2">@Model.LatestMovies.ElementAt(0).Title</h2>
                    <h3 class="carousel-h3">Release: @Model.LatestMovies.ElementAt(0).ReleaseDate.ToShortDateString()</h3>
                    <form asp-action="ShowMovie" asp-controller="Movie" asp-route-commentsPage="1" method="get">
                        <input type="hidden" name="movieId" value="@Model.LatestMovies.ElementAt(0).Id" />
                        <button type="submit" class="app-form-submit-left btn btn-danger carousel-button">SHOW MORE</button>
                    </form>
                    <form asp-action="ChooseCinemaForBooking" asp-controller="Cinema" method="get">
                        <input type="hidden" name="movieId" value="@Model.LatestMovies.ElementAt(0).Id" />
                        <button class="btn btn-warning carousel-button">BOOK A TICKET</button>
                    </form>
                </div>
                <div class="item-content-transparent col-md-7">
                    <i data-toggle="modal" data-target="#0" class="cursor-pointer glyphicon glyphicon-play-circle carousel-icon"></i><h1 class="cursor-pointer watch-trailer-h1">TRAILER</h1>
                </div>
            </div>
        </div>
        <div class="item">
            <div class="item-container-left" style="background:linear-gradient(0deg,rgba(30,30,30,0.3),rgba(30,30,30,0.3)),url(@(path + Model.LatestMovies.ElementAt(1).Id.ToString() + "Index.jpg")">
                <div class="item-content col-md-5">
                    <h2 class="carousel-h2">@Model.LatestMovies.ElementAt(1).Title</h2>
                    <h3 class="carousel-h3">Release: @Model.LatestMovies.ElementAt(1).ReleaseDate.ToShortDateString()</h3>
                    <form asp-action="ShowMovie" asp-controller="Movie" asp-route-commentsPage="1" method="get">
                        <input type="hidden" name="movieId" value="@Model.LatestMovies.ElementAt(1).Id" />
                        <button type="submit" class="app-form-submit-left btn btn-danger carousel-button">SHOW MORE</button>
                    </form>
                    <form asp-action="ChooseCinemaForBooking" asp-controller="Cinema" method="get">
                        <input type="hidden" name="movieId" value="@Model.LatestMovies.ElementAt(1).Id" />
                        <button class="btn btn-warning carousel-button">BOOK A TICKET</button>
                    </form>
                </div>
                <div class="item-content-transparent col-md-7">
                    <i data-toggle="modal" data-target="#1" class="cursor-pointer glyphicon glyphicon-play-circle carousel-icon"></i><h1 class="cursor-pointer watch-trailer-h1">TRAILER</h1>
                </div>
            </div>
        </div>
        <div class="item">
            <div class="item-container-left" style="background:linear-gradient(0deg,rgba(30,30,30,0.3),rgba(30,30,30,0.3)),url(@(path + Model.LatestMovies.ElementAt(2).Id.ToString() + "Index.jpg")">
                <div class="item-content col-md-5">
                    <h2 class="carousel-h2">@Model.LatestMovies.ElementAt(2).Title</h2>
                    <h3 class="carousel-h3">Release: @Model.LatestMovies.ElementAt(2).ReleaseDate.ToShortDateString()</h3>
                    <form class="" asp-action="ShowMovie" asp-controller="Movie" asp-route-commentsPage="1" method="get">
                        <input type="hidden" name="movieId" value="@Model.LatestMovies.ElementAt(2).Id" />
                        <button type="submit" class="app-form-submit-left btn btn-danger carousel-button">SHOW MORE</button>
                    </form>
                    <form asp-action="ChooseCinemaForBooking" asp-controller="Cinema" method="get">
                        <input type="hidden" name="movieId" value="@Model.LatestMovies.ElementAt(2).Id" />
                        <button class="btn btn-warning carousel-button">BOOK A TICKET</button>
                    </form>
                </div>
                <div class="item-content-transparent col-md-7">
                    <i data-toggle="modal" data-target="#2" class="cursor-pointer glyphicon glyphicon-play-circle carousel-icon"></i><h1 class="watch-trailer-h1">TRAILER</h1>
                </div>
            </div>
        </div>
    </div>
</div>
<br />
<div id="collapse2" class="row">
    <div class="hidden-sm hidden-xs col-lg-8 col-md-8">
        <div class="btn-group btn-group-justified" role="group" aria-label="...">
            @foreach (var category in Model.Categories)
            {

                <div class="btn-group" role="group">
                    <form method="get" asp-controller="Movie" asp-action="MoviesFromCategory">
                        <input type="hidden" name="categoryId" value="@category.Id" />
                        <button type="submit" class="btn-category btn btn-default">@category.CategoryName</button>
                    </form>
                </div>
            }
        </div>
    </div>

    <div class="col-lg-4 col-md-4">
        <form asp-action="SearchCinema" asp-controller="Cinema" method="get">
            <div class="input-group">
                <input name="city" type="text" asp- class="nav-search form-control" placeholder="Find your cinema">
                <span class="input-group-btn">
                    <button class="btn-search btn btn-danger" type="submit">SEARCH</button>
                </span>
            </div>
        </form>
    </div>
</div>
<div class="row">
    <div class="index-content col-lg-12">
        <ul class="nav nav-pills nav-justified" id="indexTab">
            <li class="active"><a data-toggle="tab" href="#newest"><i class="glyphicon glyphicon-time"></i> Newest</a></li>
            <li><a data-toggle="tab" href="#soon"><i class="glyphicon glyphicon-calendar"></i> Coming soon</a></li>
            <li><a data-toggle="tab" href="#highestRated"><i class="glyphicon glyphicon-fire"></i> Most popular</a></li>
        </ul>
        <br />
        <div class="tab-content">
            <div id="newest" class="tab-pane fade in active">
                @{
                    int j = 0;
                    foreach (var m in Model.LatestMovies)
                    {
                        j++;
                        @if ((((j - 1) % 3 == 0) && (j != 1)) || (j == 1))
                         {
                            @:<div class="row">
                         }

                        var imgSrc = "images/MoviesPosters/" + m.Id.ToString() + ".jpg";
                        <div class="col-sm-6 col-md-4">
                            <br />
                            <div class="thumbnail">
                                <a class="movie-card-a" asp-action="ShowMovie" asp-controller="Movie" asp-route-movieId="@m.Id" asp-route-commentsPage="1">
                                    <img class="movie-card-img" src="@imgSrc" alt="...">
                                    <h4>@m.Title</h4>
                                    <p>@m.Category.CategoryName</p>
                                </a>
                            </div>
                        </div>
                         @if (j % 3 == 0 || j == Model.LatestMovies.Count())
                         {
                             @:</div>
                         }
                    }
                }
            </div>
            <div id="soon" class="tab-pane fade">
                @{
                    int k = 0;
                    foreach (var m in Model.ComingSoonMovies)
                    {
                        k++;
                        @if ((((k- 1) % 3 == 0) && (k != 1)) || (k == 1))
                        {
                            @:<div class="row">
}

                        var imgSrc = "images/MoviesPosters/" + m.Id.ToString() + ".jpg";
                        <div class="col-sm-6 col-md-4">
                            <br />
                            <div class="thumbnail">
                                <a class="movie-card-a" asp-action="ShowMovie" asp-controller="Movie" asp-route-movieId="@m.Id" asp-route-commentsPage="1">
                                    <img class="movie-card-img" src="@imgSrc" alt="...">
                                    <h4>@m.Title</h4>
                                    <p>@m.Category.CategoryName</p>
                                </a>
                            </div>
                        </div>
                        @if (k % 3 == 0 || k == Model.ComingSoonMovies.Count())
                        {
                        @:</div>
                    }
                    }
                }
            </div>
            <div id="highestRated" class="tab-pane fade">
                @{
                    int l = 0;
                    foreach (var m in Model.MostPopularMovies)
                    {
                       l++;
                        @if ((((l - 1) % 3 == 0) && (l != 1)) || (l == 1))
                        {
                            @:<div class="row">
                            }

                        var imgSrc = "images/MoviesPosters/" + m.Id.ToString() + ".jpg";
                        <div class="col-sm-6 col-md-4">
                            <br />
                            <div class="thumbnail">
                                <a class="movie-card-a" asp-action="ShowMovie" asp-controller="Movie" asp-route-movieId="@m.Id" asp-route-commentsPage="1">
                                    <img class="movie-card-img" src="@imgSrc" alt="...">
                                    <h4>@m.Title</h4>
                                    <p>@m.Category.CategoryName</p>
                                </a>
                            </div>
                        </div>
                        @if (l % 3 == 0 || l == Model.MostPopularMovies.Count())
                        {
                            @:</div>
                        }
                    }
                }
            </div>
        </div>
    </div>

</div>
<br />
<br />
@{
    for (int i = 0; i <= 2; i++)
    {
        <div id="@i" class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="gridSystemModalLabel">@Model.LatestMovies.ElementAt(i).Title</h4>
                    </div>
                    <div class="modal-body">
                        <iframe height="500" src="https://www.youtube.com/embed/@Model.LatestMovies.ElementAt(i).TrailerUrl" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    </div>
                </div>
            </div>
        </div>
    }
}