StarCinema/Models/CRUDModels/IndexModels/MoviesFromCategoryViewModel.cs
using StarCinema.DomainModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StarCinema.Models.IndexModels
{
    public class MoviesFromCategoryViewModel
    {
        public string CategoryName { get; set; }
        public IEnumerable<Movie> MoviesFromCategory { get; set; }
    }
}

StarCinema/Controllers/BookingController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StarCinema.DataLayer.Abstract;
using StarCinema.DomainModels;
using StarCinema.Models;
using StarCinema.Models.CRUDModels.BookingModels;
using StarCinema.Models.CRUDModels.BookingModels.Services;

namespace StarCinema.Controllers
{
    public class BookingController : Controller
    {
        private IBookingRepository _bookingRepository;
        private IUserRepository _userRepository;
        private readonly IShowRepository _showRepository;
        private readonly IEmailBookingService _emailBookingService;
        private readonly IBookingService _bookingService;

        public BookingController(IBookingRepository bookingRepository, IUserRepository userRepository,
            IShowRepository showRepository, IEmailBookingService emailBookingService,
            IBookingService bookingService)
        {
            _bookingRepository = bookingRepository;
            _userRepository = userRepository;
            _showRepository = showRepository;
            _emailBookingService = emailBookingService;
            _bookingService = bookingService;
        }

        [Authorize]
        public IActionResult CreateBooking(int showId, string username)
        {
            var booking = new Booking()
            {
                User = _userRepository.GetUser(username),
                Show = _showRepository.GetShow(showId)
            };

            _bookingRepository.AddBooking(booking);
            _emailBookingService.SendBookingConfirmationEmail(_userRepository.GetUser(username).Email, booking);
            var bookingHash = _bookingService.GetBookingHash(booking);

            return View((object) bookingHash);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Bookings(BookingListingRequest request)
        {
            var bookings = _bookingRepository.GetPaginatedBookings(request.Page, request.PageSize, request.OrderBy, request.MovieId).ToList();
            var bookingRows = new List<BookingListingRowViewModel>();
            bookings.ForEach(x => bookingRows.Add(new BookingListingRowViewModel(x)));

            foreach (var booking in bookings)
            {
                var bookingCode = _bookingService.GetBookingHash(booking);
                bookingRows.Where(x => x.Id == booking.Id).FirstOrDefault().Code = bookingCode;
            }

            var bookingsCount = _bookingRepository.MovieBookingsCount(request.MovieId);
            var bookingListingViewModel = new ListingViewModel<BookingListingRowViewModel>(bookingRows, request.Page, bookingsCount, request.OrderBy);

            return View(bookingListingViewModel);
        }
    }
}

StarCinema/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StarCinema.DataLayer.Abstract;
using StarCinema.Models;
using StarCinema.Models.CRUDModels.CommentModels;

namespace StarCinema.Controllers
{
    public class CommentController : Controller
    {
        private readonly  ICommentRepository _commentRepository;

        public CommentController(ICommentRepository commentRepository)
        {
            _commentRepository = commentRepository;
        }

        public IActionResult MovieComments(CommentsListingRequest request)
        {
            var movieComments = _commentRepository.PaginatedComments(request.MovieId, request.Page, request.PageSize, request.OrderBy).ToList();
            var movieCommentsCount = _commentRepository.CommentsCount(request.MovieId);
            var commentsListingViewModelRows = new List<CommentsListingRowViewModel>();
            movieComments.ForEach(x => commentsListingViewModelRows.Add(new CommentsListingRowViewModel(x)));
            var commentsViewModel = new CommentListingViewModel(commentsListingViewModelRows, request.MovieId, request.Page, movieCommentsCount, request.OrderBy);
            return View(commentsViewModel);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult RemoveComment([FromQuery] RemoveCommentRequest request)
        {
            _commentRepository.RemoveComment(request.MovieId, request.CommentId);
            return RedirectToAction("MovieComments", new CommentsListingRequest(){MovieId = request.MovieId});
        }
    }
}

StarCinema/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Cors;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.Extensions.Configuration;
using StarCinema.DataLayer.Abstract;
using StarCinema.DomainModels;
using StarCinema.Models;
using StarCinema.Models.CRUDModels;
using StarCinema.Models.CRUDModels.CommentModels;
using StarCinema.Models.CRUDModels.IndexModels;
using StarCinema.Models.CRUDModels.MovieModels;
using StarCinema.Models.CRUDModels.RateModels;
using StarCinema.Models.IndexModels;

namespace StarCinema.Controllers.CRUDControllers
{
    public class MovieController : Controller
    {
        private readonly IMovieRepository _movieRepo;
        private readonly IUserRepository _usrRepo;
        private readonly ICategoryRepository _categoryRepo;
        private readonly IRateRepository _rateRepo;
        private readonly ICommentRepository _commentRepo;
        private readonly MovieFactory _movieFactory;
        private readonly CommentFactory _commentFactory;
        private readonly IConfiguration _config;
        private int _itemsPerPage;

        public MovieController(IMovieRepository movieRepo, IUserRepository usrRepo, ICategoryRepository categoryRepo, 
            IRateRepository rateRepo, ICommentRepository commentRepo, MovieFactory movieFactory, CommentFactory commentFactory, IConfiguration configuration)
        {
            this._movieRepo = movieRepo;
            this._usrRepo = usrRepo;
            this._categoryRepo = categoryRepo;
            this._rateRepo = rateRepo;
            this._commentRepo = commentRepo;
            this._movieFactory = movieFactory;
            this._commentFactory = commentFactory;
            this._config = configuration;
            this._itemsPerPage = _config.GetValue<int>("ItemsPerPage");
        }
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Movies(MovieListingRequest request)
        {
            var movies = _movieRepo.PaginatedMovies(request.Page, request.PageSize, request.OrderBy).ToList();            
            int moviesCount = this._movieRepo.MoviesCount();

            var moviesViewModel = new List<MovieListingViewModel>();

            movies.ForEach(x => moviesViewModel.Add(new MovieListingViewModel(x)));

            var paginatedMovies = new ListingViewModel<MovieListingViewModel>(moviesViewModel, request.Page, moviesCount, "TitleAsc");
            return View(paginatedMovies);
        }

        [HttpGet]
        public IActionResult MoviesFromCategory(int categoryId)
        {
            var movies = this._categoryRepo.FindMoviesFromCategory(categoryId);
            var categoryName = _categoryRepo.FindCategory(categoryId).CategoryName;
            var moviesViewModel = new MoviesFromCategoryViewModel()
            {
                CategoryName = categoryName,
                MoviesFromCategory = movies
            };

            return View(moviesViewModel);
        }

        public IActionResult ShowMovie(ShowMovieRequest request)
        {
            var movie = this._movieRepo.FindMovie(request.MovieId);
            var comments = this._commentRepo.PaginatedComments(request.MovieId, request.CommentPage, request.PageSize, "AddedDateDesc").ToList();

            var movieViewModel = new ShowMovieViewModel(movie, request.CommentPage, movie.Comments.Count());
            comments.ForEach(x => movieViewModel.Comments.Add(new ShowMovieCommentViewModel(x)));
            movieViewModel.CanUserRate = TempData["RateErrorData"] == null ? true : false;
            movieViewModel.AddComentViewModel.MovieId = request.MovieId;

            TempData["RateErrorData"] = null;
            return View(movieViewModel);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult AddMovie()
        {
            var categories = this._categoryRepo.AllCategories().ToList();
            return View(new AddEditMovieViewModel(categories));
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult AddMovie(AddEditMovieRequest request)
        {
            if (ModelState.IsValid)
            {
                var movieToAdd = _movieFactory.CreateMovie(request);

                _movieRepo.AddMovie(movieToAdd);
                int id = movieToAdd.Id;
                var filePoster = request.PosterImage;
                var fileBanner = request.BannerImage;

                ImagesManager.UploadPoster(filePoster, id, true);
                ImagesManager.UploadBanner(fileBanner, id, true);
                return RedirectToAction("Movies");
            }

            var categories = _categoryRepo.AllCategories().ToList();
            var movie = new AddEditMovieViewModel(categories, request);

            return View(movie);
        }


        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult RemoveMovie(int movieId)
        {
            var movieToDelete =  _movieRepo.FindMovie(movieId); 
            _movieRepo.RemoveMovie(movieId);
            ImagesManager.DeleteImages(movieId);
            return View(movieToDelete);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult EditMovie(int movieId)
        {
            var movie = _movieRepo.FindMovie(movieId);
            var categories = _categoryRepo.AllCategories().ToList();

            return View(new AddEditMovieViewModel(categories, movie));
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public RedirectToActionResult EditMovie(AddEditMovieViewModel addEditMovie)
        {
            var movietoEdit = _movieFactory.CreateMovie(addEditMovie.Request);

            this._movieRepo.EditMovie(addEditMovie.Request.Id, movietoEdit);

            int id = addEditMovie.Request.Id;
            var filePoster = addEditMovie.Request.PosterImage;
            var fileBanner = addEditMovie.Request.BannerImage;
            if (filePoster != null)
            { 
                ImagesManager.UploadPoster(filePoster, id, false);
            }

            if (fileBanner != null)
            { 
                ImagesManager.UploadBanner(fileBanner, id, false);
            }
            return RedirectToAction("Movies");
        }

        [Authorize]
        [HttpPost]
        public RedirectToActionResult AddComment(AddComentRequest request)
        {

            var user = this._usrRepo.GetUser(request.User);
            int id = request.MovieId;
            var commentToAdd = _commentFactory.CreateComment(request);
            
            this._movieRepo.AddComment(request.MovieId, commentToAdd);
            return RedirectToAction("ShowMovie", new ShowMovieRequest(){ MovieId = request.MovieId });
        }

        [Authorize]
        [HttpPost]
        public RedirectToActionResult AddRate(AddRateRequest request)
        {
            this.ViewData["ReturnUrl"] = "";

            var user = this._usrRepo.GetUser(request.Username);
            if (!this._rateRepo.UserRated(request.MovieId, user.Id))
            {            
                Rate rateToAdd = new Rate()
                {
                    User = user,
                    IfLike = request.ThumbUp
                }; 
                _rateRepo.AddRate(request.MovieId, rateToAdd);
                return RedirectToAction("ShowMovie", new ShowMovieRequest() { MovieId = request.MovieId });

            }
            TempData["RateErrorData"] = "You already have rated this addEditMovie";

            return RedirectToAction("ShowMovie", new ShowMovieRequest() {MovieId = request.MovieId});
        }

        [HttpGet]
        public IActionResult SearchMovies(string movieTitle)
        {
            var movies = _movieRepo.SearchMovies(movieTitle);
            var moviesSearchList = new List<SearchMoviesViewModel>();
            movies.ToList().ForEach(x => moviesSearchList.Add(new SearchMoviesViewModel(x)));
            return View(moviesSearchList);
        }
    }
}

StarCinema/Controllers/ShowController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StarCinema.DataLayer.Abstract;
using StarCinema.Models;
using StarCinema.Models.CRUDModels.ShowModel;
using StarCinema.Models.CRUDModels.ShowModels;

namespace StarCinema.Controllers
{
    public class ShowController : Controller
    {
        private readonly IShowRepository _showRepository;
        private readonly IMovieRepository _movieRepository;
        private readonly ICinemaHallRepository _cinemaHallRepository;
        private readonly ShowFactory _showFactory;
        public ShowController(IShowRepository showRepository, IMovieRepository movieRepository, 
            ICinemaHallRepository cinemaHallRepository, ShowFactory showFactory)
        {
            _showRepository = showRepository;
            _movieRepository = movieRepository;
            _cinemaHallRepository = cinemaHallRepository;
            _showFactory = showFactory;
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Shows(ShowListingRequest request)
        {
            var shows = _showRepository.GetPaginatedShows(request.MovieId, request.OrderBy, request.Page, request.PageSize).ToList();
            var showsCount = _showRepository.GetMovieShowsCount(request.MovieId);
            var showsViewModel = new List<ShowListingRowViewModel>();
            shows.ForEach(x => showsViewModel.Add(new ShowListingRowViewModel(x)));
            var showListingViewModel = new ShowListingViewModel(showsViewModel, request.Page, showsCount, request.OrderBy, request.MovieId);
            return View(showListingViewModel);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult AddShow(int movieId)
        {
            var cinemaHalls = _cinemaHallRepository.AllCinemaHalls().ToList();
            var addShowViewModel = new AddEditShowViewModel(cinemaHalls, movieId); 
            return View(addShowViewModel);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult AddShow(AddEditShowViewModel addEditShowViewModel)
        {
            var show = _showFactory.CreateShow(addEditShowViewModel.Request);
            var movieDuration = _movieRepository.FindMovie(addEditShowViewModel.Request.MovieId).DurationTime;
            bool isDateCorrect = !_showRepository.GetShowsBetweenDates(addEditShowViewModel.Request.Date,
                addEditShowViewModel.Request.Date.AddMinutes(movieDuration), addEditShowViewModel.Request.HallId).ToList().Any();

            if (!isDateCorrect)
            {
                var cinemaHalls = _cinemaHallRepository.AllCinemaHalls().ToList();
                var addShowViewModel = new AddEditShowViewModel(cinemaHalls, addEditShowViewModel.Request.MovieId);
                ModelState.AddModelError("Date", "There is already show with selected date and time");
                return View(addShowViewModel);
            }
            _showRepository.AddShow(show);
            return RedirectToAction("Shows", new ShowListingRequest(){MovieId = addEditShowViewModel.Request.MovieId});
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult RemoveShow(int showId, int MovieId)
        {
            _showRepository.DeleteShow(showId);
            return RedirectToAction("Shows", new ShowListingRequest() { MovieId = MovieId });
        }

        [HttpGet]
        [Authorize]
        public IActionResult ShowsForBooking(int movieId, int cinemaId)
        {
            var availableShows = _showRepository.GetShowsForMovieAndCinemaBetweenDates(DateTime.Now, 
                DateTime.Now.AddDays(14), cinemaId, movieId).ToList();
            
            var movieTitle = _movieRepository.FindMovie(movieId).Title;
            
            var shows = new ShowsForBookingListingViewModel(movieId, movieTitle, availableShows);

            return View(shows);
        }

    }
}

StarCinema/Views/Movie/AddMovie.cshtml
@model StarCinema.Models.CRUDModels.MovieModels.AddEditMovieViewModel;
@{
    ViewData["Title"] = "AddMovie";
    Layout = "~/Views/Shared/_CRUDLayout.cshtml";
}

<div class="row">
    <div class="col-md-6 col-md-offset-3">


        <form class="form app-form" method="post" asp-action="AddMovie" asp-controller="Movie" enctype="multipart/form-data">
            <h2 class="app-form-h2"> <i class="glyphicon glyphicon-plus"></i> Add AddEditMovie</h2>
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <input class="app-form-input" value="" placeholder="Title" asp-for="@Model.Request.Title" />
            </div>
            <div class="form-group">
                <select class="app-form-select" asp-for="@Model.Request.CategoryId" asp-items="@Model.Categories"></select>
            </div>
            <div class="form-group">
                <input class="app-form-input" value="" placeholder="Directory" asp-for="@Model.Request.Directory" />
            </div>
            <div class="form-group">
                <h4 class="app-form-h4">Release date</h4>
                <input asp-for="@Model.Request.ReleaseDate" class="form-control" value="@DateTime.Today" />
            </div>
            <div class="form-group">
                <textarea class="app-form-input wide" placeholder="Description" asp-for="@Model.Request.Description"></textarea>
            </div>
            <div class="form-group">
                <h4 class="app-form-h4">Is 3D?</h4>
                <input asp-for="@Model.Request.Is3D" class="form-control" value="false" />
                <input type="hidden" value="false" name="IncludeSalesTax" />
            </div>
            <div class="form-group">
                <h4 class="app-form-h4">Duration time</h4>
                <input asp-for="@Model.Request.DurationTime" class="app-form-input" value="150" />
            </div>
            <div class="form-group">
                <h4 class="app-form-h4">Url to trailer</h4>
                <input asp-for="@Model.Request.TrailerUrl" value="" class="app-form-input" />
            </div>
            <div class="form-group">
                <h4 class="app-form-h4">AddEditMovie poster</h4>
                <input class="form-control-file" value="" asp-for="@Model.Request.PosterImage" />
            </div>
            <div class="form-group">
                <h4 class="app-form-h4">AddEditMovie banner</h4>
                <input class="form-control-file" value="" asp-for="@Model.Request.BannerImage" />
            </div>

            <button class="btn btn-danger app-form-submit" type="submit"><i class="glyphicon glyphicon-plus"></i>ADD MOVIE</button>
        </form>
    </div>
</div>
<br />
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <form asp-action="Movies" asp-controller="Movie" asp-route-id="1" method="get">
            <button type="submit" class="btn btn-info app-form-submit"> <i class="glyphicon glyphicon-arrow-left"></i> BACK TO LIST</button>
        </form>
    </div>
</div>

StarCinema/Views/Movie/Movies.cshtml
@model StarCinema.Models.ListingViewModel<StarCinema.Models.CRUDModels.MovieModels.MovieListingViewModel>;
@{
    ViewData["Title"] = "Movies";
    Layout = "~/Views/Shared/_CRUDLayout.cshtml";
    int i = 0;
}

<h2 class="app-form-h2">AddEditMovies</h2>
<div class="row">
    <div class="col-lg-4 col-lg-offset-4">
        <form asp-action="AddMovie" asp-controller="Movie" method="get">
            <button type="submit" class="btn btn-success app-form-submit"><i class="glyphicon glyphicon-plus"></i> ADD MOVIE</button>
        </form>
    </div>
</div>
<br />
<div class="row">

    <div class="col-lg-12">

        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <td>#</td>
                        <td>Poster</td>
                        <td>
                            <a asp-controller="Movie" asp-action="Movies" asp-route-orderBy="TitleAsc">
                                <i class="glyphicon glyphicon-triangle-top"></i>
                            </a>
                            Title
                            <a asp-controller="Movie" asp-action="Movies" asp-route-orderBy="TitleDesc">
                                <i class="glyphicon glyphicon-triangle-bottom"></i>
                            </a>
                        <td>
                            <a asp-controller="Movie" asp-action="Movies" asp-route-orderBy="CategoryAsc">
                                <i class="glyphicon glyphicon-triangle-top"></i>
                            </a>
                            Category
                            <a asp-controller="Movie" asp-action="Movies" asp-route-orderBy="CategoryDesc"> 
                                <i class="glyphicon glyphicon-triangle-bottom"></i>
                            </a>
                        </td>
                        <td>
                            <a asp-controller="Movie" asp-action="Movies" asp-route-orderBy="ReleaseDateAsc">
                                <i class="glyphicon glyphicon-triangle-top"></i>
                            </a>                            
                            Release date
                            <a asp-controller="Movie" asp-action="Movies" asp-route-orderBy="ReleaseDateDesc">
                                <i class="glyphicon glyphicon-triangle-bottom"></i>
                            </a>
                        </td>
                        <td>Comments</td>
                        <td>Shows</td>
                        <td>Bookings</td>
                        <td>Action</td>
                    </tr>
                </thead>
                <tbody>
                @if (!Model.Models.Any())
                {
                    <h2>No results found</h2>
                }

                @foreach (var c in Model.Models)
                    {
                        i++;
                        var imgSrc = "/images/MoviesPosters/" + c.Id.ToString() + ".jpg";

                <tr>
                    <td>@i</td>
                    <td><img class="img-table" src="@imgSrc" /></td>
                    <td>
                        <a class="movie-card-a" asp-action="ShowMovie" asp-controller="Movie" asp-route-movieId="@c.Id">
                            @c.Title
                        </a>
                    </td>
                    <td>@c.Category</td>
                    <td>@c.ReleaseDate.ToShortDateString()</td>
                    <td>
                        <form class="app-form-table" asp-action="MovieComments" asp-controller="Comment">
                            <input type="hidden" name="movieId" value="@c.Id" />
                            <button type="submit" class="app-form-table-submit btn btn-info"><i class="glyphicon glyphicon-comment"></i> COMMENTS</button>
                        </form>
                    </td>
                    <td>
                        <form class="app-form-table" asp-action="Shows" asp-controller="Show" method="get">
                            <input type="hidden" name="movieId" value="@c.Id" />
                            <button type="submit" class="app-form-table-submit btn btn-info"><i class="glyphicon glyphicon-film"></i> SHOWS</button>
                        </form>
                    </td>
                    <td>
                        <form class="app-form-table" asp-action="Bookings" asp-controller="Booking" method="get">
                            <input type="hidden" name="movieId" value="@c.Id" />
                            <button type="submit" class="app-form-table-submit btn btn-info"><i class="glyphicon glyphicon-film"></i> BOOKINGS</button>
                        </form>
                    </td>
                    <td>
                        <form class="app-form-table" asp-action="RemoveMovie" asp-controller="Movie">
                            <input type="hidden" name="movieId" value="@c.Id" />
                            <button type="submit" class="btn btn-xs btn-danger app-form-table-submit"><i class="glyphicon glyphicon-remove"></i> DELETE</button>
                        </form>
                        <form class="app-form-table" method="get" asp-action="EditMovie" asp-controller="Movie">
                            <input type="hidden" name="movieId" value="@c.Id" />
                            <button type="submit" class="btn btn-xs btn-warning app-form-table-submit"><i class="glyphicon glyphicon-pencil"></i> EDIT</button>
                        </form>
                    </td>
                </tr>
                    }
                </tbody>
            </table>


        </div>
    </div>
</div>


@{
    int nextPage = Model.PagingInfo.CurrentPage == Model.PagingInfo.TotalPages ? Model.PagingInfo.CurrentPage : Model.PagingInfo.CurrentPage + 1;
    int prevPage = Model.PagingInfo.CurrentPage == 1 ? Model.PagingInfo.CurrentPage : Model.PagingInfo.CurrentPage - 1;
    int startPage = Model.PagingInfo.CurrentPage >= 10 ? Model.PagingInfo.CurrentPage : 1;
}


<div class="row">
    <div class="col-sm-12">
        <nav>
            <ul class="pagination">
                <li class="page-item">
                    <a asp-action="Movies" asp-controller="Movie" asp-route-orderBy="@Model.OrderBy" asp-route-page="1" class="page-link">
                        <i class="glyphicon glyphicon-fast-backward"></i>
                    </a>
                </li>
                <li class="page-item">
                    <a asp-action="Movies" asp-controller="Movie" asp-route-orderBy="@Model.OrderBy" asp-route-page="@prevPage" class="page-link"><i class="glyphicon glyphicon-backward"></i></a>
                </li>

                @for (int j = startPage; j <= Model.PagingInfo.TotalPages; j++)
                {
                    if (j == Model.PagingInfo.CurrentPage)
                    {
                        <li class="page-item active"><a asp-action="Movies" asp-controller="Movie" asp-route-orderBy="@Model.OrderBy" asp-route-page="@j" class="page-link">@j</a></li>
                    }
                    else
                    {
                        <li class="page-item"><a asp-action="Movies" asp-controller="Movie" asp-route-orderBy="@Model.OrderBy"  asp-route-page="@j" class="page-link">@j</a></li>
                    }
                }
                <li class="page-item">
                    <a asp-action="Movies" asp-controller="Movie" asp-route-orderBy="@Model.OrderBy" asp-route-page="@nextPage" class="page-link"><i class="glyphicon glyphicon-forward"></i></a>
                </li>
                <li class="page-item">
                    <a asp-action="Movies" asp-controller="Movie" asp-route-orderBy="@Model.OrderBy" asp-route-page="@Model.PagingInfo.TotalPages" class="page-link"><i class="glyphicon glyphicon-fast-forward"></i></a>
                </li>
            </ul>
        </nav>
    </div>
</div>

StarCinema/Views/Movie/MoviesFromCategory.cshtml
@model StarCinema.Models.IndexModels.MoviesFromCategoryViewModel
@{
    ViewData["Title"] = "MoviesFromCategory";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-xs-12">
        <h2><i class="glyphicon glyphicon-th-lis"></i> @Model.CategoryName</h2>
        <hr />
    </div>
</div>

@foreach (var movie in Model.MoviesFromCategory)
{
    var imgSrc = "../../images/MoviesPosters/" + movie.Id + ".jpg";
    <div class="row list-movie-panel">
        <div class="col-md-3">
            <img class="" src="@imgSrc" alt="...">
        </div>
        <div class="col-md-9">
            <a class="movie-card-a" asp-action="ShowMovie" asp-controller="Movie" asp-route-id="@movie.Id">
                <h2><i class="glyphicon glyphicon-film"></i> @movie.Title</h2>
            </a>
                <h4><i class="glyphicon glyphicon-calendar"></i> Release: @movie.ReleaseDate.ToShortDateString()</h4>
                <p>@movie.Description</p>
                <h4><i class="glyphicon glyphicon-comment"></i> Comments: @movie.Comments.Count</h4>
                <form method="get" asp-action="ShowMovie" asp-controller="Movie">
                    <input type="hidden" name="movieId" value="@movie.Id" />
                    <button class="btn btn-warning btn-big"> <i class="glyphicon glyphicon-zoom-in"></i> SHOW MORE</button>
                </form>
                <br />
        </div>
    </div>
    <br />
}

StarCinema/Views/Movie/RemoveMovie.cshtml
@model StarCinema.DomainModels.Movie
@{
    ViewData["Title"] = "RemoveMovie";
    Layout = "~/Views/Shared/_CRUDLayout.cshtml";
}

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h2 class="app-form-h2"> <i class="glyphicon glyphicon-ok"></i> Successfully removed addEditMovie @Model.Title (id = @Model.Id) </h2>
        <form asp-action="Movies" asp-controller="Movie" method="get">
            <button type="submit" class="btn btn-info app-form-submit"> <i class="glyphicon glyphicon-arrow-left"></i> BACK TO LIST</button>
        </form>
    </div>
</div>